sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

haxe:
  - "3.2.1"
  - "3.4.4"
  - development

env:
  - HAXE_TARGET=cpp
  - HAXE_TARGET=cs
  - HAXE_TARGET=flash
  - HAXE_TARGET=lua
  - HAXE_TARGET=neko
  - HAXE_TARGET=node
  - HAXE_TARGET=php
  - HAXE_TARGET=php7
  - HAXE_TARGET=python
  - HAXE_TARGET=js
  - HAXE_TARGET=java

matrix:
  fast_finish: true
  allow_failures:
    - haxe: development
    - haxe: "3.2.1"
      env: HAXE_TARGET=cpp
    - haxe: "3.2.1"
      env: HAXE_TARGET=lua
  exclude:
    - haxe: "3.2.1"
      env: HAXE_TARGET=php7
    - haxe: "3.4.4"
      env: HAXE_TARGET=php7
    - haxe: development
      os: osx

install:
  - haxelib git travix https://github.com/back2dos/travix && pushd . && cd $(haxelib config)travix/git && haxe build-neko.hxml && popd
  - haxelib run travix install
  - haxelib install hx3compat
  - haxelib install munit
  - haxelib install tink_testrunner

script:
  - haxelib run travix $HAXE_TARGET
